name: Run build and create release
on:
  push:
    branches:
    - master
    - dev
jobs:
  run:
    runs-on: windows-latest
    steps:
    - run: echo ("LATEST=" + ("${{github.ref_name}}" -eq "master")) >> $env:GITHUB_ENV
    - run: echo ("PRERELEASE=" + ("${{github.ref_name}}" -eq "dev")) >> $env:GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.3.0
      with:
          node-version: '23.9.0'
    - run: npm install
    - run: echo ("VERSION=" + (node -p "require('./package.json').version")) >> $env:GITHUB_ENV
    - run: npm run build:win
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/dipped_mc-${{ env.VERSION }}-setup.exe
        release_name: v${{ env.VERSION }}
        tag: v${{ env.VERSION }}
        overwrite: true
        file_glob: true
        make_latest: ${{ env.LATEST }}
        prerelease: ${{ env.PRERELEASE }}
