name: Run build and create release
on:
  push:
    branches:
    - master
jobs:
  run:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.3.0
      with:
          node-version: '>=23.9.0'
    - run: npm install
    - run: npm run make
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: v.${{ secrets.GITHUB_TOKEN }}
        file: out/make/squirrel.windows/x64/* # the folder which has all the files that you want to release
        tag: ${{ steps.package-version.outputs.current-version }}
        overwrite: true
        file_glob: true
