name: Run build and create release
on:
  push:
    branches:
    - master
jobs:
  run:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.3.0
      with:
          node-version: '>=23.9.0'
    - run: npm install
    - run: echo "VERSION=$(npm pkg get version)" >> $GITHUB_OUTPUT
      id: version
    - run: npm run make
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: out/make/squirrel.windows/x64/*
        tag: v.${{ steps.version.outputs.VERSION }}
        overwrite: true
        file_glob: true
